story_description = "Novel about the duality of artificial intelligence (inspired by the duality of man)"
genre = "historical fiction"
tone = "analytical and introspective"
themes = ["duality", "artificial intelligence", "humanity"]
main_character_name = "Nikolai"
# authors_message = 